name: CI
on: [push, pull_request]

env:
  TASK_PYTHON: '3.12'

jobs:

  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.12', '3.13']
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1
      - uses: taiki-e/install-action@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0 (just)
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: uv sync --locked --dev
      - run: just
